# Generated by Django 5.1.1 on 2024-10-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Kaustubh Harapanahalli", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(default="MS Student", max_length=255),
                ),
                (
                    "institution",
                    models.CharField(
                        default="Arizona State University", max_length=255
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="homepage/images/"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="kharapan [at] asu [dot] edu", max_length=255
                    ),
                ),
            ],
        ),
    ]
